01-all solutions
js-tasks-ru/vue-20210304_kiphirrr pull request #3
Opened 2021-03-25 17:40 UTC by kiphir

2021-03-25 17:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-03-27 12:48 UTC, kiphir commented
@ShGKme первый блок на проверку

2021-03-27 19:33 UTC, ShGKme requested changes
Требуется избавиться от XSS и побочных эффектов в вычисляемом свойстве

2021-03-27 19:33 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/index.html
> +            <p class="meetup-description" v-html="meetup.description"></p>
`v-html` выведет значение как html без какого-либо экранирования. Это потенциальный [XSS](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D1%81%D0%B0%D0%B9%D1%82%D0%BE%D0%B2%D1%8B%D0%B9_%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B8%D0%BD%D0%B3).

Любой пользователь может сделать свой митап с любым заголовком, в том числе использовать там теги или внедрять скрипты. С `v-html` получится серьёзная дыра в безопасности.

Правильнее использовать обычные выражения `{{ value }}`.

Если так было сделано из-за `<s>` в названии одного из докладов, то это оригинальное название: [https://vueconf.us/schedule/](https://vueconf.us/schedule/). `All you need is <s>love</s> Apollo Client`

Но наличие таких названий не должно приводить к XSS

2021-03-27 19:33 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/index.html
> +                <h5 class="meetup-agenda__title" v-html="agendaItem.title ? agendaItem.title : agendaItem.typeTitle"></h5>
XSS

2021-03-27 19:33 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/index.html
> +                <p v-if="agendaItem.description" v-html="agendaItem.description"></p>
XSS

2021-03-27 19:33 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/script.js
> +      }
Это вычисляемое свойство не вычисляет новый объект на основе данных компонента, а изменяет данные компонента. Так делать ни в коем случае нельзя. Вычисляемое свойство не должно иметь побочных эффектов. Оно должно только возвращать вычисленное значение.

Сейчас это происходит, потому что в переменную `meetup` сохранена ссылка на объект в `this.rawMeetup`. Иными словами, `meetup === this.rawMeetup`, это ссылка на один и тот же объект. Изменение свойств у `meetup` приводит к изменению свойств у `this.rawMeetup`

2021-04-11 15:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-04-11 15:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-04-11 15:45 UTC, kiphir commented
@ShGKme поправил

2021-04-11 19:32 UTC, ShGKme reviewed
Обновления приняты, но требуется решить все добавленные задачи, чтобы PR был принят

2021-04-18 16:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-02 19:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-02 19:20 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-03 16:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-05-03 16:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-05-06 19:51 UTC, merged